import img1 from "../../assets/images/successStory/1.jpg";
export const successData = [
  {
    id: 0,
    title:
      "Shital B.K. : A journey from Budakot Achham to London United Kingdom",
    description:
      " Shital is a 16-year-old Chairperson of Bajinath Girls Empowerment Group        in Budakot, Achham. The group was formed by SAMABIKAS Nepal comprising        25 girls to empower them and as a strategy for curbing child-marriage.        Coming from a tiny village where early and child marriage is common,        Shital is determined to break the cycle and make education a priority.        She is in her 10th standard and is passionate about fighting for girls’        rights, and acts as a voice for every girl searching for meaning. Last        year, Shital attended 3-day Gender and Leadership training provided by        SAMABIKAS Nepal. Among all the trainees, Shital was determined to bring        a change in herself and her family. She describes her time at her home        was tough because she had to convince each family member that she will        not stay in a menstrual hut and follow the menstrual taboos. But now she        believes that her commitment has set her apart and made her who she is        today. She is truly an example of the saying; change starts from within.        In this one and half year time Shital has transformed herself from a        member of the group to a leader of the group and this year she is the        local resource person, who now leads, monitors, and coordinates        interactive sessions with girls aged 12 to 19. Because of her        outstanding performance among all the 125 adolescent girls group, she        was chosen as a girl leader by SAMABIKAS Nepal to visit an award        ceremony conducted by With and For Girls in London on March 2020. Now,        she is also in charge of taking weekly BLOP classes to her friends and        earns income that she uses to buy her school supplies. She skillfully        plans, speaks, creates an agenda, and leads the meetings. One of the        major achievements is that recently, Shital and her group inspired other        girls (who are not in the group formed by SAMABIKAS Nepal) to make a        commitment by lighting oil lamps as a promise to stay against child        marriage and break all menstrual taboos. She consistently seeks        opportunities for leadership and is committed to being a young leader        and works to empower girls and educate on their rights.",
  },
  {
    id: 1,
    title: "Sima Bhul: Child bride to girl leader       ",
    description:
      "I am Sima Bhul and I come from a small rural municipality called Chaurpati. I live with my parents and four siblings. My father is a farmer and my mother is a homemaker who sometimes helps my father in the field. Last year, one of my community members came to me and requested me to be part of this girl’s group. It was a very new concept to me as I have never had knowledge of its comprehensive community-based program. She informed me about SAMABIKAS Nepal that conducts Better Life Options Program class, education, and vocational skills programs for girls and young women. Now I feel like joining the girl’s group might have been one of the best decisions of my life as it has boosted my self-esteem.\nOnly a few months ago, I was under a lot of pressure from my parents and siblings to accept a suitor, marry and help ease the family financial strains during the COVID-19 pandemic. At first, I was confused, shocked and upset, all at once when my parents accepted on my behalf. I remember making several calls to the community volunteers and to SAMABIKAS Nepal, just to be clear on whether my decision to reject the proposal was the right one or not. Despite the intense pressure from my community elders, I made a decision myself to avoid marriage and stay in school. With the help of BLOP class, Gender and Leadership Training I was aware of my rights and it is illegal for my parents to force me into getting married at such a tender age. Hence, I decided to reach out for help and my parents gave up on my wedding plans.\nCurrently I am well known in my community as the girl who chose her studies over getting married. Over this month I have attended trainings, health camps and even given an interview on a TV program. I have also earned few pennies which I used for my school supplies and to buy a gas cylinder as we were cooking on a firewood. Thanks to SAMABIKAS Nepal’s activities they conduct in my village and inspire me and other girls to make decisions for themselves. ",
    image: img1,
  },
];
